version: '3'
services:
  php:
    image: bitnami/php-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - ./www:/app
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - 80:8080
      - 443:8443
    environment:
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8443
    volumes:
    - ./hosts/:/vhosts:ro
    - ./www:/app
    - ./conf/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
    - ./conf/httpdrewrite.conf:/opt/bitnami/apache/conf/httpdrewrite.conf